------------------------- MODULE pessimisticl_lock -------------------------
(***************************************************************************)
(* Algorithm to perform a single step action in an external system in a    *)
(* concurrency resilient way.  It is assumed that the third party allows   *)
(* us to introduce a unique way to identify the action in all of its       *)
(* steps.                                                                  *)
(*                                                                         *)
(* It is also needed to have a central locking storage.                    *)
(*                                                                         *)
(* The resulting algorithm should:                                         *)
(*                                                                         *)
(* - Guarantee that only one instance of the process attempts the action.  *)
(*                                                                         *)
(* - Be able to recover from a failed previous attempt.                    *)
(*                                                                         *)
(* - Prevent double booking if two process attempt the same action against *)
(* the same resouce.                                                       *)
(*                                                                         *)
(* - As a consequence, it should be idempotent.                            *)
(*                                                                         *)
(* The third party must provide:                                           *)
(*                                                                         *)
(* - A mechanism to add metadata to the process, and subsequently query it *)
(* based on that data, in order to identify it.                            *)
(***************************************************************************)

(***************************************************************************)
(* The process will be modelled after an integration with a third party    *)
(* that creates customer support tickets for users that report a bug in    *)
(* the product.                                                            *)
(*                                                                         *)
(* A ticket has to eventually be created for every bug.                    *)
(*                                                                         *)
(* Only one ticket can be created per bug.                                 *)
(***************************************************************************)



=============================================================================
